### ISSUE TITLE
Real-time video stream application

### ISSUE THREAD

**Issue by CCamouflage-Hvv** [TomTomTommi/bidastereo#3]
Great Work!
I am wondering if this method can handle video stream in real-time?

**Comment by TomTomTommi** [comment]
Hi, currently the model is off-line, where t-1 and t+1 frames are utilized. The simplest way for real-time or online model is to change the bidirectional mode to single directional mode and use a smaller model. Plus, you can based on [bidavideo](https://github.com/TomTomTommi/bidavideo) to use a real-time raftstereo.

**Comment by CCamouflage-Hvv** [comment]
Thanks for ur reply!!!!!
Is that means I can try to modify Bidavideo's stablizer to single directional mode and plugin it into some real-time stereo network?

**Comment by TomTomTommi** [comment]
yes, that's it.

**Comment by Langwenchong** [comment]
@TomTomTommi Dear Author,

Hello! I came across your earlier works BiDAStereo and BiDAVideo after reading your other paper Stereo Any Video. As I am currently working on real-time, online, and stable video depth estimation, I found that the ideas in BiDA can effectively address this problem. Therefore, I would like to discuss several detailed questions with you:

1.Both BiDAStereo and BiDAVideo share a similar core idea: they build a local three-layer cost volume based on optical flow alignment and use a frame-by-frame bidirectional propagation hidden state update module for global alignment. BiDAVideo further simplifies this process by directly encoding disparity maps aligned between adjacent frames and constructing a module similar to MRU, thereby simplifying the TFCL module. Is my understanding correct?

2.Since BiDAVideo uses bidirectional propagation, estimating the stable disparity of frame t requires both frame t-1 and t. If I want to estimate from a real-time video stream, based on your above approach, would it be sufficient to modify the flow_warp stage of BiDAVideo to discard the backward propagation and retrain the model using only the forward direction?

3.In the parameter settings of demo.py, I would like to ask about the relationship between frame_size and kernel_size. 

![Image](https://github.com/user-attachments/assets/cafc14b2-d791-492e-9020-afc4551a1522)

If I want to perform depth alignment using only 3 consecutive frames each time, how should I modify these parameters?

Furthermore, I noticed that Stereo Any Video doesn’t explicitly incorporate the BiDA concept. It seems to only introduce video depth priors through features from Video Depth Anything. Why didn’t you further integrate BiDA methods in this work?

**Comment by TomTomTommi** [comment]
Hi @Langwenchong,

1. BiDAVideo introduces a stabilizer concept to enhance the temporal consistency of image-based stereo models. This stabilizer does not include a correlation module, as it focuses solely on refining the disparity maps. Therefore, it may not be accurate to say it “simplifies” TFCL, since TFCL refers specifically to the correlation component.

2. Yes, exactly. You can use only the previous time step without requiring the future frame.

3. Frame size refers to the total number of frames in a video sequence, which needs to be limited to avoid memory issues. Kernel size, on the other hand, defines how many frames are processed together and is directly related to GPU memory usage. To properly support online settings, it's recommended to redesign the architecture file rather than just modifying these parameters.

4. The motivation behind Stereo Any Video is different from BiDAVideo. It aims to bypass the limitations of auxiliary networks, such as those relying on camera pose or optical flow, by designing a framework that does not depend on them.
